#!/usr/bin/env python3
"""Audit structural coverage separately from source and matching readiness."""
from __future__ import annotations

import argparse
import csv
import io
import re
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGETS = ROOT / "analysis" / "progress_targets.csv"
SYMBOLS = ROOT / "analysis" / "symbols.csv"
P16_TARGETS = ROOT / "analysis" / "progress16_recovered_targets.csv"
P17_TARGETS = ROOT / "analysis" / "progress17_recovered_targets.csv"
P16_PSEUDOCODE = ROOT / "analysis" / "functions" / "progress16_r5900_pseudocode.c.txt"
P17_PSEUDOCODE = ROOT / "analysis" / "functions" / "progress17_r5900_pseudocode.c.txt"
PROMOTIONS = ROOT / "analysis" / "source_promotions.csv"
CSV_OUT = ROOT / "analysis" / "source_readiness.csv"
DOC_OUT = ROOT / "docs" / "SOURCE_COMPLETENESS.generated.md"

EXPECTED_STRUCTURAL_TARGETS = 1041
EXPECTED_P16_PSEUDOCODE = 165
EXPECTED_P17_PSEUDOCODE = 74
MARKER_RE = re.compile(r"^/\* ===== (0x[0-9a-fA-F]{8}) ===== \*/$", re.MULTILINE)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as stream:
        return list(csv.DictReader(stream))


def fail(message: str) -> None:
    raise SystemExit(f"source audit failed: {message}")


def unique_by_address(rows: list[dict[str, str]], label: str) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for row in rows:
        address = row["address"].lower()
        if address in result:
            fail(f"duplicate {label} address {address}")
        result[address] = row
    return result


def pseudocode_markers(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    markers = [match.lower() for match in MARKER_RE.findall(text)]
    if len(markers) != len(set(markers)):
        fail(f"duplicate address marker in {path.relative_to(ROOT)}")
    return set(markers)


def explicit_source_references(addresses: set[str]) -> tuple[dict[str, list[str]], int]:
    """Return conservative address-to-source traceability, not ownership proof."""
    references: dict[str, list[str]] = defaultdict(list)
    translation_units = sorted((ROOT / "src").rglob("*.c"))
    address_by_hex = {address[2:]: address for address in addresses}

    for path in translation_units:
        text = path.read_text(encoding="utf-8", errors="replace").lower()
        relative = path.relative_to(ROOT).as_posix()
        for token, address in address_by_hex.items():
            if token in text:
                references[address].append(relative)

    return dict(references), len(translation_units)


def render_csv(
    target_rows: list[dict[str, str]],
    p16: set[str],
    p17: set[str],
    references: dict[str, list[str]],
) -> str:
    stream = io.StringIO(newline="")
    fields = [
        "address",
        "name",
        "area",
        "manifest_status",
        "source_form",
        "explicit_src_reference",
        "source_files",
        "matching_status",
    ]
    writer = csv.DictWriter(stream, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    for row in target_rows:
        address = row["address"].lower()
        if address in p16:
            source_form = "STRUCTURAL_PSEUDOCODE_P16"
        elif address in p17:
            source_form = "STRUCTURAL_PSEUDOCODE_P17"
        else:
            source_form = "BEHAVIORAL_SOURCE_MODEL"
        files = references.get(address, [])
        writer.writerow(
            {
                "address": address,
                "name": row["name"],
                "area": row["area"],
                "manifest_status": row["status"],
                "source_form": source_form,
                "explicit_src_reference": "yes" if files else "no",
                "source_files": ";".join(files),
                "matching_status": "MATCHING" if row["status"] == "MATCHING" else "UNPROVEN",
            }
        )
    return stream.getvalue()


def render_doc(
    total: int,
    behavioral: int,
    p16_count: int,
    p17_count: int,
    promoted: int,
    explicit: int,
    translation_units: int,
    matching: int,
) -> str:
    pseudo = p16_count + p17_count

    def pct(value: int) -> str:
        return f"{value * 100.0 / total:.2f}%"

    return f"""# Generated source-completeness audit

> Generated by `tools/audit_source_completeness.py`. Do not hand-edit this file.

The repository has complete **structural representation** for the audited target
universe, but it does not yet contain a complete build-ready, byte-matching
replacement program. These are deliberately separate measurements.

| Measurement | Result | What it proves |
|---|---:|---|
| Audited structural entries | **{total:,}/{total:,} ({pct(total)})** | Every validated entry has a committed structural representation. |
| Behavioral/source-model checkpoint | **{behavioral:,}/{total:,} ({pct(behavioral)})** | Typed behavioral/source-model reconstruction exists; this is not automatically compiler-ready or exact. |
| Structural pseudocode only | **{pseudo:,}/{total:,} ({pct(pseudo)})** | These entries still require typed, build-ready C/C++ migration: {p16_count} remaining from Progress 16 and {p17_count} remaining from Progress 17. |
| Typed promotions from P16/P17 snapshots | **{promoted:,}** | Historical pseudocode evidence is retained while newer typed source overrides the readiness classification. |
| Explicit address trace in `src/` | **{explicit:,}/{total:,} ({pct(explicit)})** | A conservative text-level traceability check; corridor files may cover additional entries without repeating every address. |
| C translation units tracked | **{translation_units} files** | `make host-syntax` parses each independently on the host. That check does not prove EE linking or target behavior. |
| Relocation-normalized machine-code matches | **{matching:,}/{total:,} ({pct(matching)})** | No function is promoted to `MATCHING` without generated-object evidence. |
| Complete replacement ELF | **No** | Startup ownership, globals/types, object boundaries, linker script/order, historical archives and packing still need proof. |

## Invariants checked

- `analysis/progress_targets.csv` and `analysis/symbols.csv` contain the same
  {total:,} addresses, names, statuses, confidence values and notes.
- All {total:,} manifest rows are structurally reconstructed.
- The historical {EXPECTED_P16_PSEUDOCODE} Progress-16 and {EXPECTED_P17_PSEUDOCODE} Progress-17 manifest sets exactly match the
  address markers in their committed pseudocode snapshots.
- `analysis/source_promotions.csv` contains {promoted} typed promotion(s); every
  promoted address belongs to a historical pseudocode checkpoint and names an
  existing source/evidence file. The source file must explicitly carry the
  promoted address token.
- No address occurs in both pseudocode checkpoints.

The machine-readable row-by-row classification is
[`analysis/source_readiness.csv`](../analysis/source_readiness.csv).

## Meaning of “complete”

“Nothing left behind” is currently defensible only inside the closed structural
universe: 1,137 raw JAL-shaped targets − 292 rejected post-code data patterns +
196 independently mapped non-JAL entries = 1,041 validated entries. It does not
prove that 1,041 is the mathematically exact number of compiler-created
functions, nor that the original source has already been recovered verbatim.

The next proof ladder is documented in
[`docs/MATCHING_WORKFLOW.md`](MATCHING_WORKFLOW.md).
"""


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists():
            fail(f"missing generated file {path.relative_to(ROOT)}")
        if path.read_text(encoding="utf-8") != content:
            fail(f"stale generated file {path.relative_to(ROOT)}; run make audit-source")
        return
    path.write_text(content, encoding="utf-8", newline="")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated audit files are stale")
    args = parser.parse_args()

    target_rows = read_csv(TARGETS)
    symbol_rows = read_csv(SYMBOLS)
    targets = unique_by_address(target_rows, "progress target")
    symbols = unique_by_address(symbol_rows, "symbol")

    if len(target_rows) != EXPECTED_STRUCTURAL_TARGETS:
        fail(f"expected {EXPECTED_STRUCTURAL_TARGETS} targets, found {len(target_rows)}")
    if set(targets) != set(symbols):
        fail("progress and symbol manifests have different address sets")
    for address, target in targets.items():
        symbol = symbols[address]
        for field in ("name", "status", "confidence", "notes"):
            if target[field] != symbol[field]:
                fail(f"manifest mismatch at {address}: {field}")

    statuses = Counter(row["status"] for row in target_rows)
    unexpected = set(statuses) - {"RECONSTRUCTED", "MATCHING"}
    if unexpected:
        fail(f"non-reconstructed statuses remain: {sorted(unexpected)}")

    p16_rows = unique_by_address(read_csv(P16_TARGETS), "Progress-16 target")
    p17_rows = unique_by_address(read_csv(P17_TARGETS), "Progress-17 target")
    p16 = set(p16_rows)
    p17 = set(p17_rows)
    if len(p16) != EXPECTED_P16_PSEUDOCODE:
        fail(f"expected {EXPECTED_P16_PSEUDOCODE} Progress-16 rows, found {len(p16)}")
    if len(p17) != EXPECTED_P17_PSEUDOCODE:
        fail(f"expected {EXPECTED_P17_PSEUDOCODE} Progress-17 rows, found {len(p17)}")
    if p16 & p17:
        fail(f"pseudocode checkpoints overlap at {sorted(p16 & p17)[0]}")
    if not (p16 | p17) <= set(targets):
        fail("pseudocode checkpoint contains an address outside the structural manifest")
    if p16 != pseudocode_markers(P16_PSEUDOCODE):
        fail("Progress-16 CSV and pseudocode address markers differ")
    if p17 != pseudocode_markers(P17_PSEUDOCODE):
        fail("Progress-17 CSV and pseudocode address markers differ")

    promotion_rows = unique_by_address(read_csv(PROMOTIONS), "source promotion")
    promoted = set(promotion_rows)
    historical_pseudocode = p16 | p17
    if not promoted <= historical_pseudocode:
        fail("source promotion contains an address outside the historical pseudocode checkpoints")
    for address, row in promotion_rows.items():
        source_rel = row.get("source_file", "").strip()
        evidence_rel = row.get("evidence", "").strip()
        if not source_rel:
            fail(f"source promotion {address} has no source_file")
        if not evidence_rel:
            fail(f"source promotion {address} has no evidence")
        source_path = ROOT / source_rel
        evidence_path = ROOT / evidence_rel
        if not source_path.is_file():
            fail(f"source promotion {address} references missing source {source_rel}")
        if not evidence_path.is_file():
            fail(f"source promotion {address} references missing evidence {evidence_rel}")
        source_text = source_path.read_text(encoding="utf-8", errors="replace").lower()
        if address[2:] not in source_text:
            fail(f"source promotion {address} is not explicitly traced in {source_rel}")

    p16_remaining = p16 - promoted
    p17_remaining = p17 - promoted
    references, translation_units = explicit_source_references(set(targets))
    behavioral = len(target_rows) - len(p16_remaining) - len(p17_remaining)
    matching = statuses.get("MATCHING", 0)
    csv_text = render_csv(target_rows, p16_remaining, p17_remaining, references)
    doc_text = render_doc(
        len(target_rows),
        behavioral,
        len(p16_remaining),
        len(p17_remaining),
        len(promoted),
        len(references),
        translation_units,
        matching,
    )
    write_or_check(CSV_OUT, csv_text, args.check)
    write_or_check(DOC_OUT, doc_text, args.check)

    action = "verified" if args.check else "wrote"
    print(
        f"{action} source audit: structural={len(target_rows)}/{len(target_rows)} "
        f"behavioral_source_model={behavioral} "
        f"pseudocode_only={len(p16_remaining) + len(p17_remaining)} promoted={len(promoted)} "
        f"explicit_src_trace={len(references)} matching={matching} translation_units={translation_units}"
    )


if __name__ == "__main__":
    main()
