#!/usr/bin/env python3
"""Close the P16/P17 source-model backlog with a deterministic low-level C lift.

This tool does *not* claim original-source recovery or machine-code matching.
It converts the already-committed, address-labelled Ghidra R5900 snapshots into
host-parseable target-width C while preserving their control flow, warnings,
absolute-symbol names, call labels and address evidence.

The output is deliberately a low-level decompilation/source model.  Existing
hand-recovered source promotions win: addresses already promoted to another
source file are never replaced by this generated corridor.
"""
from __future__ import annotations

import argparse
import csv
import io
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
P16_TARGETS = ROOT / "analysis" / "progress16_recovered_targets.csv"
P17_TARGETS = ROOT / "analysis" / "progress17_recovered_targets.csv"
P16_SNAPSHOT = ROOT / "analysis" / "functions" / "progress16_r5900_pseudocode.c.txt"
P17_SNAPSHOT = ROOT / "analysis" / "functions" / "progress17_r5900_pseudocode.c.txt"
PROGRESS_TARGETS = ROOT / "analysis" / "progress_targets.csv"
PROMOTIONS = ROOT / "analysis" / "source_promotions.csv"
OUTPUT_REL = "src/ps2/progress28_structural_lift_recovered.c"
OUTPUT = ROOT / OUTPUT_REL
PROGRESS_DOC = ROOT / "docs" / "PROGRESS28.md"
FAILURE_DIR = ROOT / "build" / "progress28"
FAILURE_SOURCE = FAILURE_DIR / "failed.c"
FAILURE_LOG = FAILURE_DIR / "compiler.log"

# Evidence-backed return-type correction: Progress 27 already models 0x0012bf5c
# as the float curve used by the neighboring DSP transform. Ghidra emitted this
# one header as void even though call sites consume its value.
RETURN_TYPE_OVERRIDES = {
    "snes_p28_0012bf5c": "float",
}

EXPECTED_P16 = 165
EXPECTED_P17 = 74
EXPECTED_HISTORICAL = EXPECTED_P16 + EXPECTED_P17

MARKER_RE = re.compile(r"^/\* ===== (0x[0-9a-fA-F]{8}) ===== \*/\s*$", re.MULTILINE)
FUNCTION_RE = re.compile(
    r"(?ms)^[ \t]*"
    r"(?P<ret>[A-Za-z_][A-Za-z0-9_ \t\*]*?)"
    r"[ \t]+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)*)"
    r"\s*\((?P<params>.*?)\)\s*\n\s*\{"
)

GLOBAL_RE = re.compile(
    r"\b(?:"
    r"_?DAT_[0-9A-Fa-f]+|"
    r"(?:p?(?:u|i|b|c|s|us|f|d|l|ul)Ram)[0-9A-Fa-f]+|"
    r"PTR_[A-Za-z0-9_]+|"
    r"REG_[A-Za-z0-9_]+|"
    r"switchdataD_[A-Za-z0-9_]+"
    r")\b"
)

TYPE_PREAMBLE = r"""/*
 * Progress 28: buildable low-level source lift for the remaining historical
 * Progress-16/17 R5900 decompilation snapshots.
 *
 * Generated by tools/close_structural_source.py from evidence already tracked
 * in analysis/functions/.  The bodies retain Ghidra's conservative register,
 * DAT_*, RAM and call labels.  This is decompiled behavioral/source-model C,
 * not the original SNES Station source and not a machine-code MATCHING claim.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wimplicit-function-declaration"
#pragma GCC diagnostic ignored "-Wint-conversion"
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
#pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
#pragma GCC diagnostic ignored "-Wincompatible-pointer-types"
#pragma GCC diagnostic ignored "-Woverflow"
#endif

typedef uint8_t undefined;
typedef uint8_t undefined1;
typedef uint16_t undefined2;
typedef uint32_t undefined3;
typedef uint32_t undefined4;
typedef uint64_t undefined5;
typedef uint64_t undefined6;
typedef uint64_t undefined7;
typedef uint64_t undefined8;
/* Ghidra can spell non-native integer widths in casts (for example uint5). */
typedef uint32_t uint3;
typedef int32_t int3;
typedef uint64_t uint5;
typedef int64_t int5;
typedef uint64_t uint6;
typedef int64_t int6;
typedef uint64_t uint7;
typedef int64_t int7;
#if defined(__SIZEOF_INT128__)
typedef __uint128_t p28_u128;
typedef __uint128_t undefined9;
typedef __uint128_t undefined10;
typedef __uint128_t undefined11;
typedef __uint128_t undefined12;
typedef __uint128_t undefined13;
typedef __uint128_t undefined14;
typedef __uint128_t undefined15;
typedef __uint128_t undefined16;
#else
#error "Progress-28 low-level lift requires unsigned __int128 support for R5900-wide temporaries"
#endif

typedef uint8_t byte;
typedef int8_t sbyte;
typedef uint8_t uchar;
typedef int8_t schar;
typedef uint16_t ushort;
typedef uint32_t uint;
typedef uint64_t ulong;
typedef uint64_t ulonglong;
typedef int64_t longlong;
typedef uint16_t word;
typedef uint32_t dword;
typedef uint64_t qword;
typedef float float4;
typedef double float8;
typedef long double float10;

/*
 * Ghidra's `code *` means an unresolved callable target.  An old-style
 * function type intentionally accepts the unknown target ABI at this source
 * recovery stage.
 */
typedef uint64_t code();

static p28_u128 p28_mask_bytes(unsigned bytes)
{
    if (bytes >= 16u)
        return ~(p28_u128)0;
    if (bytes == 0u)
        return (p28_u128)0;
    return (((p28_u128)1u << (bytes * 8u)) - (p28_u128)1u);
}

static p28_u128 p28_concat(p28_u128 hi, p28_u128 lo, unsigned lo_bytes)
{
    return (hi << (lo_bytes * 8u)) | (lo & p28_mask_bytes(lo_bytes));
}

static p28_u128 p28_subpiece(p28_u128 value, unsigned byte_offset, unsigned out_bytes)
{
    return (value >> (byte_offset * 8u)) & p28_mask_bytes(out_bytes);
}

static p28_u128 p28_sign_extend(p28_u128 value, unsigned in_bytes)
{
    const unsigned bits = in_bytes * 8u;
    p28_u128 mask;
    p28_u128 sign;

    if (bits == 0u || bits >= 128u)
        return value;

    mask = (((p28_u128)1u << bits) - (p28_u128)1u);
    sign = (p28_u128)1u << (bits - 1u);
    value &= mask;
    return (value ^ sign) - sign;
}

static p28_u128 p28_load_blob(const void *src, size_t bytes)
{
    const unsigned char *in = (const unsigned char *)src;
    p28_u128 value = 0;
    size_t i;

    if (bytes > 16u)
        bytes = 16u;
    for (i = 0; i < bytes; ++i)
        value |= (p28_u128)in[i] << (i * 8u);
    return value;
}

static void p28_store_blob(void *dst, p28_u128 value, size_t bytes)
{
    unsigned char *out = (unsigned char *)dst;
    size_t i;

    if (bytes > 16u)
        bytes = 16u;
    for (i = 0; i < bytes; ++i)
        out[i] = (unsigned char)(value >> (i * 8u));
}

static void p28_copy_blob(void *dst, const void *src, size_t bytes)
{
    unsigned char *out = (unsigned char *)dst;
    const unsigned char *in = (const unsigned char *)src;
    size_t i;

    for (i = 0; i < bytes; ++i)
        out[i] = in[i];
}

static p28_u128 p28_read_piece(
    const void *src,
    size_t object_bytes,
    unsigned byte_offset,
    unsigned piece_bytes)
{
    const unsigned char *in = (const unsigned char *)src;
    p28_u128 value = 0;
    unsigned i;

    if (byte_offset >= object_bytes)
        return 0;
    if (piece_bytes > 16u)
        piece_bytes = 16u;
    if ((size_t)byte_offset + piece_bytes > object_bytes)
        piece_bytes = (unsigned)(object_bytes - byte_offset);

    for (i = 0; i < piece_bytes; ++i)
        value |= (p28_u128)in[byte_offset + i] << (i * 8u);
    return value;
}

static void p28_write_piece(
    void *dst,
    size_t object_bytes,
    unsigned byte_offset,
    unsigned piece_bytes,
    p28_u128 value)
{
    unsigned char *out = (unsigned char *)dst;
    unsigned i;

    if (byte_offset >= object_bytes)
        return;
    if (piece_bytes > 16u)
        piece_bytes = 16u;
    if ((size_t)byte_offset + piece_bytes > object_bytes)
        piece_bytes = (unsigned)(object_bytes - byte_offset);

    for (i = 0; i < piece_bytes; ++i)
        out[byte_offset + i] = (unsigned char)(value >> (i * 8u));
}
"""


@dataclass(frozen=True)
class LiftFunction:
    address: str
    snapshot: str
    manifest_name: str
    area: str
    original_name: str
    return_type: str
    params: str
    raw_chunk: str


def fail(message: str) -> "None":
    raise SystemExit(f"Progress-28 closure failed: {message}")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as stream:
        return list(csv.DictReader(stream))


def unique_rows(rows: list[dict[str, str]], label: str) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for row in rows:
        address = row["address"].lower()
        if address in result:
            fail(f"duplicate {label} address {address}")
        result[address] = row
    return result


def split_snapshot(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    matches = list(MARKER_RE.finditer(text))
    result: dict[str, str] = {}
    for index, match in enumerate(matches):
        address = match.group(1).lower()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        if address in result:
            fail(f"duplicate marker {address} in {path.relative_to(ROOT)}")
        result[address] = text[start:end].strip() + "\n"
    return result


def parse_function(
    address: str,
    chunk: str,
    snapshot: str,
    target: dict[str, str],
) -> LiftFunction:
    match = FUNCTION_RE.search(chunk)
    if match is None:
        fail(f"could not parse C-like function header for {address} in {snapshot}")
    return LiftFunction(
        address=address,
        snapshot=snapshot,
        manifest_name=target["name"],
        area=target["area"],
        original_name=match.group("name"),
        return_type=" ".join(match.group("ret").split()),
        params=match.group("params").strip(),
        raw_chunk=chunk,
    )


def replace_identifier(text: str, old: str, new: str) -> str:
    if "::" in old:
        return text.replace(old, new)
    return re.sub(rf"\b{re.escape(old)}\b", new, text)


def normalize_scopes(text: str) -> str:
    # Failed Ghidra jumptable recovery can print C++-scope syntax in a C file.
    # Preserve the table label but lower the spelling to a normal C identifier.
    text = re.sub(
        r"&[A-Za-z_][A-Za-z0-9_]*::(switchdataD_[A-Za-z0-9_]+)",
        r"\1",
        text,
    )
    while "::" in text:
        newer = re.sub(
            r"\b([A-Za-z_][A-Za-z0-9_]*)::([A-Za-z_][A-Za-z0-9_]*)\b",
            r"\1_\2",
            text,
        )
        if newer == text:
            break
        text = newer
    return text


def normalize_array_casts(text: str) -> str:
    aliases = {
        1: "uint8_t",
        2: "uint16_t",
        3: "uint32_t",
        4: "uint32_t",
        5: "uint64_t",
        6: "uint64_t",
        7: "uint64_t",
        8: "uint64_t",
        9: "p28_u128",
        10: "p28_u128",
        11: "p28_u128",
        12: "p28_u128",
        13: "p28_u128",
        14: "p28_u128",
        15: "p28_u128",
        16: "p28_u128",
    }

    def repl(match: re.Match[str]) -> str:
        width = int(match.group(1))
        return f"({aliases.get(width, 'p28_u128')})"

    return re.sub(
        r"\(\s*undefined\s*\[\s*(\d+)\s*\]\s*\)",
        repl,
        text,
    )


def array_locals(text: str) -> dict[str, int]:
    result: dict[str, int] = {}
    for match in re.finditer(
        r"(?m)^[ \t]*undefined[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
        r"[ \t]*\[[ \t]*(\d+)[ \t]*\][ \t]*;",
        text,
    ):
        result[match.group(1)] = int(match.group(2))
    return result


def rewrite_array_assignments(text: str) -> str:
    arrays = array_locals(text)

    for name in sorted(arrays, key=len, reverse=True):
        pattern = re.compile(
            rf"(?ms)^([ \t]*){re.escape(name)}[ \t]*=[ \t]*(.*?);"
        )

        def repl(match: re.Match[str], name: str = name) -> str:
            expression = match.group(2).strip()

            # A match that crossed a block boundary is not a plain assignment.
            if "\n}" in expression or "\ncase " in expression or "\ndefault:" in expression:
                return match.group(0)

            if expression in arrays:
                return (
                    f"{match.group(1)}p28_copy_blob({name}, {expression}, "
                    f"sizeof({name}));"
                )
            return (
                f"{match.group(1)}p28_store_blob({name}, "
                f"(p28_u128)({expression}), sizeof({name}));"
            )

        text = pattern.sub(repl, text)

    scalar_types = (
        "byte|sbyte|uchar|schar|ushort|uint|ulong|long|int|short|"
        "undefined1|undefined2|undefined3|undefined4|undefined5|"
        "undefined6|undefined7|undefined8|p28_u128"
    )
    for name in sorted(arrays, key=len, reverse=True):
        text = re.sub(
            rf"\((?P<type>{scalar_types})\)[ \t]*{re.escape(name)}\b(?![ \t]*\[)",
            rf"(\g<type>)p28_load_blob({name}, sizeof({name}))",
            text,
        )
    return text


def parse_width_pair(digits: str, relation: str) -> tuple[int, int] | None:
    legal = {1, 2, 3, 4, 5, 6, 7, 8, 12, 16}
    candidates: list[tuple[int, int]] = []
    for split in range(1, len(digits)):
        left = int(digits[:split])
        right = int(digits[split:])
        if left not in legal or right not in legal:
            continue
        if relation == "concat" and left + right <= 16:
            candidates.append((left, right))
        elif relation == "sub" and right <= left:
            candidates.append((left, right))
        elif relation == "extend" and left <= right:
            candidates.append((left, right))
    return candidates[0] if candidates else None


def intrinsic_macros(text: str) -> str:
    lines: list[str] = []

    for token in sorted(set(re.findall(r"\b(CONCAT\d+)\s*\(", text))):
        pair = parse_width_pair(token[6:], "concat")
        if pair is None:
            continue
        _high_bytes, low_bytes = pair
        lines.append(
            f"#define {token}(hi, lo) "
            f"p28_concat((p28_u128)(hi), (p28_u128)(lo), {low_bytes}u)"
        )

    for token in sorted(set(re.findall(r"\b(SUB\d+)\s*\(", text))):
        pair = parse_width_pair(token[3:], "sub")
        if pair is None:
            continue
        _input_bytes, output_bytes = pair
        lines.append(
            f"#define {token}(value, off) "
            f"p28_subpiece((p28_u128)(value), (unsigned)(off), {output_bytes}u)"
        )

    for kind in ("ZEXT", "SEXT"):
        for token in sorted(set(re.findall(rf"\b({kind}\d+)\s*\(", text))):
            pair = parse_width_pair(token[len(kind):], "extend")
            if pair is None:
                continue
            input_bytes, _output_bytes = pair
            if kind == "ZEXT":
                lines.append(
                    f"#define {token}(value) "
                    f"((p28_u128)(value) & p28_mask_bytes({input_bytes}u))"
                )
            else:
                lines.append(
                    f"#define {token}(value) "
                    f"p28_sign_extend((p28_u128)(value), {input_bytes}u)"
                )

    for kind in ("CARRY", "SCARRY", "SBORROW"):
        tokens = sorted(set(re.findall(rf"\b({kind}(?:1|2|4|8))\s*\(", text)))
        for token in tokens:
            width = int(token[len(kind):])
            bits = width * 8
            if kind == "CARRY":
                lines.append(
                    f"#define {token}(a, b) "
                    f"((((p28_u128)(a) & p28_mask_bytes({width}u)) + "
                    f"((p28_u128)(b) & p28_mask_bytes({width}u))) > "
                    f"p28_mask_bytes({width}u))"
                )
            elif kind == "SCARRY":
                signed = f"int{bits}_t"
                lines.append(
                    f"#define {token}(a, b) "
                    f"((({signed})(a) > 0 && ({signed})(b) > "
                    f"INT{bits}_MAX - ({signed})(a)) || "
                    f"(({signed})(a) < 0 && ({signed})(b) < "
                    f"INT{bits}_MIN - ({signed})(a)))"
                )
            else:
                signed = f"int{bits}_t"
                lines.append(
                    f"#define {token}(a, b) "
                    f"((({signed})(a) < 0 && ({signed})(b) > 0 && "
                    f"({signed})((a) - (b)) > 0) || "
                    f"(({signed})(a) >= 0 && ({signed})(b) < 0 && "
                    f"({signed})((a) - (b)) < 0))"
                )

    return "\n".join(lines)


def infer_global_decl(name: str, text: str) -> str:
    if name.startswith("REG_"):
        return f"extern volatile uint64_t {name};"
    if name.startswith("switchdataD_"):
        return f"extern uintptr_t {name}[];"
    if name.startswith("PTR_s_"):
        return f"extern const char *{name};"
    if name.startswith("PTR_"):
        # PTR_* labels are target pointer values.  Keeping non-subscripted
        # labels as integer addresses avoids invalid C for decompiler arithmetic
        # such as `integer - PTR_*`; explicit casts still determine memory width.
        if re.search(rf"\b{re.escape(name)}\s*\[", text):
            return f"extern unsigned char *{name};"
        return f"extern uintptr_t {name};"

    pointer_prefixes = (
        ("puRam", "uint32_t"),
        ("piRam", "int32_t"),
        ("pbRam", "uint8_t"),
        ("pcRam", "char"),
        ("psRam", "int16_t"),
        ("pusRam", "uint16_t"),
        ("pfRam", "float"),
        ("pdRam", "double"),
        ("plRam", "int64_t"),
        ("pulRam", "uint64_t"),
    )
    for prefix, ctype in pointer_prefixes:
        if name.startswith(prefix):
            return f"extern {ctype} *{name};"

    scalar_prefixes = (
        ("uRam", "uint32_t"),
        ("iRam", "int32_t"),
        ("bRam", "uint8_t"),
        ("cRam", "char"),
        ("sRam", "int16_t"),
        ("usRam", "uint16_t"),
        ("fRam", "float"),
        ("dRam", "double"),
        ("lRam", "int64_t"),
        ("ulRam", "uint64_t"),
    )
    for prefix, ctype in scalar_prefixes:
        if name.startswith(prefix):
            return f"extern {ctype} {name};"

    # If Ghidra directly subscripts an unresolved DAT symbol, a byte pointer is
    # the least-committal compilable representation.  Explicit casts in the
    # decompile still control the actual access width.
    if re.search(rf"\b{re.escape(name)}\s*\[", text):
        return f"extern unsigned char *{name};"

    return f"extern uint64_t {name};"


def rewrite_partial_storage_accesses(text: str) -> str:
    # Ghidra can spell register subpieces as `value._4_2_`.  That notation is
    # useful evidence but is not C.  Lower writes first, then reads, through
    # byte-addressed helpers so both scalar and byte-array temporaries work.
    write_pattern = re.compile(
        r"(?ms)^([ \t]*)([A-Za-z_][A-Za-z0-9_]*)"
        r"\._(\d+)_(\d+)_[ \t]*=[ \t]*(.*?);"
    )

    def write_repl(match: re.Match[str]) -> str:
        expression = match.group(5).strip()
        if "\n}" in expression or "\ncase " in expression or "\ndefault:" in expression:
            return match.group(0)
        name = match.group(2)
        return (
            f"{match.group(1)}p28_write_piece(&{name}, sizeof({name}), "
            f"{int(match.group(3))}u, {int(match.group(4))}u, "
            f"(p28_u128)({expression}));"
        )

    text = write_pattern.sub(write_repl, text)
    text = re.sub(
        r"\b([A-Za-z_][A-Za-z0-9_]*)\._(\d+)_(\d+)_",
        lambda match: (
            f"p28_read_piece(&{match.group(1)}, sizeof({match.group(1)}), "
            f"{int(match.group(2))}u, {int(match.group(3))}u)"
        ),
        text,
    )
    return text


SCALAR_TYPE_RE = re.compile(
    r"^(?:const\s+|volatile\s+)*(?:"
    r"undefined(?:1|2|3|4|5|6|7|8)?|byte|sbyte|uchar|schar|ushort|uint|ulong|"
    r"longlong|ulonglong|word|dword|qword|char|short|int|long|float|double|"
    r"float4|float8|float10|uint8_t|uint16_t|uint32_t|uint64_t|"
    r"int8_t|int16_t|int32_t|int64_t|uintptr_t|p28_u128"
    r")$"
)


def split_top_level_commas(text: str) -> list[str]:
    parts: list[str] = []
    start = 0
    paren = bracket = brace = 0
    for index, char in enumerate(text):
        if char == "(":
            paren += 1
        elif char == ")" and paren:
            paren -= 1
        elif char == "[":
            bracket += 1
        elif char == "]" and bracket:
            bracket -= 1
        elif char == "{":
            brace += 1
        elif char == "}" and brace:
            brace -= 1
        elif char == "," and paren == 0 and bracket == 0 and brace == 0:
            parts.append(text[start:index].strip())
            start = index + 1
    tail = text[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def parameter_name(declaration: str) -> str | None:
    declaration = declaration.strip()
    if declaration in {"", "void", "..."}:
        return None
    match = re.search(
        r"([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\]\s*)?$",
        declaration,
    )
    return match.group(1) if match is not None else None


def scalar_declarations(text: str) -> dict[str, str]:
    """Collect scalar parameter/local types for address-use lowering."""
    result: dict[str, str] = {}
    header = FUNCTION_RE.search(text)
    if header is not None:
        for declaration in split_top_level_commas(header.group("params")):
            name = parameter_name(declaration)
            if name is None or "*" in declaration or "[" in declaration:
                continue
            prefix = declaration[: declaration.rfind(name)].strip()
            if SCALAR_TYPE_RE.match(prefix):
                result[name] = prefix

    local_re = re.compile(
        r"(?m)^[ \t]*(?P<type>(?:const[ \t]+|volatile[ \t]+)*"
        r"(?:undefined(?:1|2|3|4|5|6|7|8)?|byte|sbyte|uchar|schar|ushort|uint|ulong|"
        r"longlong|ulonglong|word|dword|qword|char|short|int|long|float|double|"
        r"float4|float8|float10|uint8_t|uint16_t|uint32_t|uint64_t|"
        r"int8_t|int16_t|int32_t|int64_t|uintptr_t|p28_u128))"
        r"[ \t]+(?P<name>[A-Za-z_][A-Za-z0-9_]*)[ \t]*(?:;|=)"
    )
    for match in local_re.finditer(text):
        result.setdefault(match.group("name"), " ".join(match.group("type").split()))
    return result


def _unary_deref_pattern(name: str) -> re.Pattern[str]:
    return re.compile(
        rf"(?m)(?P<prefix>^[ \t]*|[\[=(:,;{{}}!&|?+\-/%<>][ \t]*)"
        rf"\*[ \t]*{re.escape(name)}\b"
    )


def rewrite_scalar_address_uses(text: str) -> str:
    """Lower scalar-as-address artifacts without changing scalar arithmetic."""
    declarations = scalar_declarations(text)
    for name, ctype in sorted(declarations.items(), key=lambda item: len(item[0]), reverse=True):
        text = re.sub(
            rf"\b{re.escape(name)}[ \t]*\[",
            f"(({ctype} *)(uintptr_t)({name}))[",
            text,
        )
        pattern = _unary_deref_pattern(name)
        text = pattern.sub(
            lambda m, name=name, ctype=ctype: (
                f"{m.group('prefix')}*({ctype} *)(uintptr_t)({name})"
            ),
            text,
        )
        text = re.sub(
            rf"\breturn[ \t]+\*[ \t]*{re.escape(name)}\b",
            f"return *({ctype} *)(uintptr_t)({name})",
            text,
        )
    return text


def rewrite_global_direct_dereferences(text: str) -> str:
    names = sorted(set(GLOBAL_RE.findall(text)), key=len, reverse=True)
    for name in names:
        if name.startswith("puRam"):
            ctype = "uint32_t"
        elif name.startswith("piRam"):
            ctype = "int32_t"
        elif name.startswith("pusRam"):
            ctype = "uint16_t"
        elif name.startswith("psRam"):
            ctype = "int16_t"
        elif name.startswith("pbRam"):
            ctype = "uint8_t"
        elif name.startswith("pcRam"):
            ctype = "char"
        elif name.startswith("pfRam"):
            ctype = "float"
        elif name.startswith("pdRam"):
            ctype = "double"
        elif name.startswith("pulRam"):
            ctype = "uint64_t"
        elif name.startswith("plRam"):
            ctype = "int64_t"
        else:
            ctype = "uint8_t"
        pattern = _unary_deref_pattern(name)
        text = pattern.sub(
            lambda m, name=name, ctype=ctype: (
                f"{m.group('prefix')}*({ctype} *)(uintptr_t)({name})"
            ),
            text,
        )
    return text


def lower_function_definition_to_old_style(text: str, address: str) -> str:
    """Use a K&R definition so stripped call arity cannot become a fatal error."""
    match = FUNCTION_RE.search(text)
    if match is None:
        fail(f"cannot lower function definition for {address}")

    ret = " ".join(match.group("ret").split())
    name = match.group("name")
    ret = RETURN_TYPE_OVERRIDES.get(name, ret)
    params_text = match.group("params").strip()
    if params_text in {"", "void"}:
        replacement = f"{ret} {name}()\n{{"
    else:
        declarations = split_top_level_commas(params_text)
        names: list[str] = []
        for declaration in declarations:
            param = parameter_name(declaration)
            if param is None:
                return text
            names.append(param)
        replacement = (
            f"{ret} {name}({', '.join(names)})\n" +
            "\n".join(f"{decl};" for decl in declarations) +
            "\n{"
        )
    return text[: match.start()] + replacement + text[match.end():]


def normalize_chunk(text: str, address: str | None = None) -> str:
    # 0x0012bf5c is decompiled as void, but its caller consumes the result of
    # FUN_001a3cc0 as a float.  Preserve that observed return dataflow rather
    # than fabricating a constant merely to satisfy host C.
    if address == "0x0012bf5c":
        text = re.sub(
            r"(?m)^[ \t]*FUN_001a3cc0\(uVar1\);[ \t]*\n[ \t]*return;",
            "  return (float)FUN_001a3cc0(uVar1);",
            text,
            count=1,
        )
    text = normalize_scopes(text)
    text = rewrite_partial_storage_accesses(text)
    text = normalize_array_casts(text)
    text = rewrite_array_assignments(text)
    text = rewrite_scalar_address_uses(text)
    text = rewrite_global_direct_dereferences(text)
    if address is not None:
        text = lower_function_definition_to_old_style(text, address)
    return text


def function_prototype(text: str, address: str) -> str:
    match = FUNCTION_RE.search(text)
    if match is not None:
        ret = " ".join(match.group("ret").split())
        name = match.group("name")
    else:
        # Progress-28 lowers managed definitions to old-style K&R syntax after
        # normalization.  At this point we only need return type + symbol name
        # for the deliberately non-prototyped forward declaration.
        fallback = re.search(
            r"(?m)^[ \t]*(?P<ret>[A-Za-z_][A-Za-z0-9_ \t\*]*?)"
            r"[ \t]+(?P<name>snes_p28_[0-9a-fA-F]+)\s*\(",
            text,
        )
        if fallback is None:
            fail(f"transformed function {address} no longer has a parseable header")
        ret = " ".join(fallback.group("ret").split())
        name = fallback.group("name")

    # Ghidra's call-site recovery is intentionally weaker than its function-body
    # recovery: a stripped call can be rendered with missing/extra arguments.
    # A strict prototype would turn that known decompiler limitation into a C
    # compile error.  Old-style C declaration syntax keeps the recovered return
    # type/name while deliberately leaving call arity unspecified.  The real
    # definition below still preserves the parameters observed for the target.
    return f"{ret} {name}();"


def extra_array_tokens(text: str) -> set[str]:
    return set(re.findall(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\[", text))


def assemble_source(
    body: str,
    prototypes: list[str],
    dynamic_scalars: set[str] | None = None,
    dynamic_types: set[str] | None = None,
) -> str:
    dynamic_scalars = dynamic_scalars or set()
    dynamic_types = dynamic_types or set()

    globals_found = sorted(set(GLOBAL_RE.findall(body)))
    globals_text = "\n".join(infer_global_decl(name, body) for name in globals_found)
    intrinsic_text = intrinsic_macros(body)

    # Subscripted undeclared register/table labels are made byte arrays.  Local
    # declarations shadow these harmless conservative externs.
    known_globals = set(globals_found)
    arrays = sorted(
        name for name in extra_array_tokens(body)
        if (
            name.startswith(("switchdataD_", "PTR_", "DAT_", "_DAT_"))
            and name not in known_globals
        )
    )
    array_text = "\n".join(f"extern unsigned char {name}[];" for name in arrays)

    dynamic_type_text = "\n".join(
        f"typedef uint64_t {name};" for name in sorted(dynamic_types)
    )
    dynamic_scalar_text = "\n".join(
        f"extern uint64_t {name};" for name in sorted(dynamic_scalars)
    )

    parts = [
        TYPE_PREAMBLE.rstrip(),
        "/* Ghidra intrinsic lowerings used by this generated corridor. */",
        intrinsic_text,
        "/* Conservative declarations for unresolved absolute target symbols. */",
        globals_text,
        array_text,
        dynamic_type_text,
        dynamic_scalar_text,
        "/* Forward declarations preserve calls between lifted functions. */",
        "\n".join(prototypes),
        body.rstrip(),
        "",
    ]
    return "\n\n".join(part for part in parts if part != "")


def parse_compiler_repairs(stderr: str) -> tuple[set[str], set[str]]:
    undeclared: set[str] = set()
    types: set[str] = set()

    # GCC/Clang can use ASCII quotes or Unicode curly quotes depending locale.
    for match in re.finditer(
        r"(?:['‘])([A-Za-z_][A-Za-z0-9_]*)(?:['’]) undeclared",
        stderr,
    ):
        undeclared.add(match.group(1))
    for match in re.finditer(
        r"unknown type name\s+(?:['‘])([A-Za-z_][A-Za-z0-9_]*)(?:['’])",
        stderr,
    ):
        types.add(match.group(1))
    return undeclared, types


def compiler_error_summary(stderr: str, source: str, limit: int = 24) -> str:
    """Return a compact source-aware summary of fatal compiler diagnostics."""
    source_lines = source.splitlines()
    diagnostics: list[str] = []
    seen: set[tuple[int, str]] = set()

    error_re = re.compile(r"^(.*?):(\d+):(\d+):\s+(?:fatal\s+)?error:\s+(.*)$")
    for raw in stderr.splitlines():
        match = error_re.match(raw)
        if match is None:
            continue
        line_no = int(match.group(2))
        message = match.group(4).strip()
        key = (line_no, message)
        if key in seen:
            continue
        seen.add(key)
        diagnostics.append(f"line {line_no}: error: {message}")
        start = max(1, line_no - 1)
        end = min(len(source_lines), line_no + 1)
        for n in range(start, end + 1):
            marker = ">" if n == line_no else " "
            diagnostics.append(f"  {marker} {n:05d} | {source_lines[n - 1]}")
        if len(seen) >= limit:
            break

    if not diagnostics:
        diagnostics.append("compiler returned failure but no parsable `error:` diagnostic was found")
    return "\n".join(diagnostics)


def preserve_failure_artifacts(source: str, stderr: str) -> None:
    FAILURE_DIR.mkdir(parents=True, exist_ok=True)
    FAILURE_SOURCE.write_text(source, encoding="utf-8", newline="")
    FAILURE_LOG.write_text(stderr, encoding="utf-8", newline="")


def clear_failure_artifacts() -> None:
    FAILURE_SOURCE.unlink(missing_ok=True)
    FAILURE_LOG.unlink(missing_ok=True)
    if FAILURE_DIR.exists():
        for path in FAILURE_DIR.glob("attempt-*.c"):
            path.unlink(missing_ok=True)
        for path in FAILURE_DIR.glob("attempt-*.log"):
            path.unlink(missing_ok=True)
    try:
        FAILURE_DIR.rmdir()
    except OSError:
        pass


def preserve_attempt(attempt: int, source: str, stderr: str) -> None:
    FAILURE_DIR.mkdir(parents=True, exist_ok=True)
    (FAILURE_DIR / f"attempt-{attempt:02d}.c").write_text(
        source, encoding="utf-8", newline=""
    )
    (FAILURE_DIR / f"attempt-{attempt:02d}.log").write_text(
        stderr, encoding="utf-8", newline=""
    )


def _diagnostic_source_lines(stderr: str) -> list[tuple[int, str]]:
    result: list[tuple[int, str]] = []
    regex = re.compile(r"^.*?:(\d+):\d+:\s+(?:fatal\s+)?error:\s+(.*)$")
    for raw in stderr.splitlines():
        match = regex.match(raw)
        if match is not None:
            result.append((int(match.group(1)), match.group(2).strip()))
    return result


def _cast_bracket_indices(line: str) -> str:
    pattern = re.compile(r"\[([^\[\]]+)\]")
    return pattern.sub(lambda m: f"[(uintptr_t)({m.group(1)})]", line)


def _cast_scalar_subscript_base(line: str) -> str:
    pattern = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\[([^\[\]]+)\]")
    return pattern.sub(
        lambda m: (
            f"((uint8_t *)(uintptr_t)({m.group(1)}))"
            f"[(uintptr_t)({m.group(2)})]"
        ),
        line,
    )


def _repair_indirect_callable(line: str) -> str:
    """Restore an unresolved callable cast after scalar address lowering."""
    pattern = re.compile(
        r"\(\*\([^\n()]+\*\)\(uintptr_t\)\((?P<target>[A-Za-z_][A-Za-z0-9_]*)\)\)\("
    )
    return pattern.sub(
        lambda m: f"(*(code *)(uintptr_t)({m.group('target')}))(",
        line,
    )


def _repair_pointer_subtraction(line: str) -> str:
    """Make target-address subtraction explicit when Ghidra mixed C types."""
    symbol = r"(?:_?DAT_[0-9A-Fa-f]+|PTR_[A-Za-z0-9_]+)"
    ident = r"[A-Za-z_][A-Za-z0-9_]*"
    line = re.sub(
        rf"\b(?P<left>{ident})\s*-\s*(?P<right>{symbol})\b",
        lambda m: (
            f"((uintptr_t)({m.group('left')}) - "
            f"(uintptr_t)({m.group('right')}))"
        ),
        line,
    )
    line = re.sub(
        rf"\b(?P<left>{symbol})\s*-\s*(?P<right>{ident})\b",
        lambda m: (
            f"((uintptr_t)({m.group('left')}) - "
            f"(uintptr_t)({m.group('right')}))"
        ),
        line,
    )
    return line


def apply_line_diagnostic_repairs(body: str, source: str, stderr: str) -> tuple[str, int]:
    """Apply only syntax/type repairs explicitly requested by compiler errors."""
    source_lines = source.splitlines()
    body_lines = body.splitlines()
    changed = 0

    for line_no, message in _diagnostic_source_lines(stderr):
        if not (1 <= line_no <= len(source_lines)):
            continue
        original = source_lines[line_no - 1]
        replacement = original

        if "array subscript is not an integer" in message:
            replacement = _cast_bracket_indices(original)
        elif "subscripted value is neither array nor pointer nor vector" in message:
            replacement = _cast_scalar_subscript_base(original)
        elif "called object is not a function or function pointer" in message:
            replacement = _repair_indirect_callable(original)
        elif "invalid operands to binary -" in message:
            replacement = _repair_pointer_subtraction(original)

        if replacement == original:
            continue
        matches = [i for i, line in enumerate(body_lines) if line == original]
        if not matches:
            continue
        for index in matches:
            body_lines[index] = replacement
        changed += len(matches)

    suffix = "\n" if body.endswith("\n") else ""
    return "\n".join(body_lines) + suffix, changed


def verify_with_compiler(
    body: str,
    prototypes: list[str],
    compiler: str,
) -> str:
    dynamic_scalars: set[str] = set()
    dynamic_types: set[str] = set()
    last_stderr = ""
    body_current = body
    clear_failure_artifacts()

    for _attempt in range(1, 33):
        source = assemble_source(body_current, prototypes, dynamic_scalars, dynamic_types)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            suffix=".c",
            prefix="progress28-",
            dir=ROOT,
            delete=False,
        ) as stream:
            stream.write(source)
            temporary = Path(stream.name)

        try:
            result = subprocess.run(
                [
                    compiler,
                    "-std=c11",
                    "-Wall",
                    "-Wextra",
                    "-fsyntax-only",
                    "-I",
                    str(ROOT / "include"),
                    str(temporary),
                ],
                cwd=ROOT,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
        except OSError as exc:
            fail(f"could not execute host compiler {compiler!r}: {exc}")
        finally:
            temporary.unlink(missing_ok=True)

        if result.returncode == 0:
            clear_failure_artifacts()
            return source

        last_stderr = result.stderr
        preserve_attempt(_attempt, source, result.stderr)
        undeclared, unknown_types = parse_compiler_repairs(result.stderr)
        undeclared -= dynamic_scalars
        unknown_types -= dynamic_types

        # Do not turn C keywords into declarations if a compiler diagnostic was
        # unusually phrased.
        undeclared -= {
            "if", "else", "for", "while", "do", "switch", "case", "return",
            "sizeof", "void", "int", "long", "short", "char", "float", "double",
        }

        repaired_body, line_repairs = apply_line_diagnostic_repairs(
            body_current, source, result.stderr
        )
        if line_repairs:
            body_current = repaired_body

        if not undeclared and not unknown_types and line_repairs == 0:
            break
        dynamic_scalars.update(undeclared)
        dynamic_types.update(unknown_types)

    preserve_failure_artifacts(source, last_stderr)
    print("Progress-28 compiler gate still has fatal diagnostics:")
    print(compiler_error_summary(last_stderr, source))
    print(f"full generated C: {FAILURE_SOURCE.relative_to(ROOT)}")
    print(f"full compiler log: {FAILURE_LOG.relative_to(ROOT)}")
    fail("generated low-level lift did not pass host C syntax; no promotion files were changed")


def promotion_csv(
    existing_rows: list[dict[str, str]],
    managed_addresses: set[str],
    lifted: list[LiftFunction],
) -> str:
    fields = ["address", "source_file", "evidence", "notes"]
    kept = [
        row for row in existing_rows
        if row["address"].lower() not in managed_addresses
    ]

    additions = []
    for function in sorted(lifted, key=lambda item: int(item.address, 16)):
        evidence = (
            "analysis/functions/progress16_r5900_pseudocode.c.txt"
            if function.snapshot == "P16"
            else "analysis/functions/progress17_r5900_pseudocode.c.txt"
        )
        additions.append(
            {
                "address": function.address,
                "source_file": OUTPUT_REL,
                "evidence": evidence,
                "notes": (
                    "Progress 28 target-width buildable low-level C lift from "
                    f"{function.snapshot} R5900 decompile; warnings/control flow "
                    "preserved; no machine-code matching claim"
                ),
            }
        )

    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=fields, lineterminator="\n")
    writer.writeheader()
    writer.writerows(kept)
    writer.writerows(additions)
    return stream.getvalue()


def render_progress_doc(
    lifted: list[LiftFunction],
    preexisting: int,
    compiler: str,
) -> str:
    p16 = sum(function.snapshot == "P16" for function in lifted)
    p17 = sum(function.snapshot == "P17" for function in lifted)
    total_after = preexisting + len(lifted)

    return f"""# Progress 28 — structural-source mega closure

Progress 28 converts the remaining committed Progress-16/17 R5900 decompiler
snapshots into one deterministic, host-parseable low-level C corridor.

## Scope

- pre-existing hand-reviewed P16/P17 promotions: **{preexisting}**
- Progress-28 lifted entries: **{len(lifted)}**
  - Progress 16: **{p16}**
  - Progress 17: **{p17}**
- historical P16/P17 entries represented by typed/buildable source after this
  step: **{total_after}/{EXPECTED_HISTORICAL}**

The generator verifies the combined translation unit with `{compiler} -std=c11 -Wall -Wextra -fsyntax-only` before changing the promotion registry.
`make audit-source` and `make check` remain the repository-wide gates.

## What this closes

The generated source preserves the target-address labels, decompiled control
flow, Ghidra warning comments, unresolved call labels and target-width scalar
operations.  Failed Ghidra jumptable scope spellings and non-C array-value casts
are lowered mechanically without inventing higher-level behavior.

When all {EXPECTED_HISTORICAL} historical P16/P17 addresses are promoted, the
source audit should report **1,041/1,041 behavioral/source-model entries** and
**0 structural-pseudocode-only entries**.

## What this does not prove

This is **not** a claim that the original SNES Station source text, class
boundaries, global types or source-file organization have been recovered
verbatim.  Conservative `DAT_*`/RAM declarations remain where the stripped
binary does not prove a better type.  It is also **not** compiler matching:
the relocation-normalized MATCHING count is unchanged unless a separate
historical-EE object comparison proves otherwise.

The immutable P16/P17 snapshots remain the evidence record behind this generated
corridor.
"""


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content, encoding="utf-8", newline="")
    temporary.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--compiler",
        default=os.environ.get("HOST_CC", "cc"),
        help="host C compiler used as the syntax gate (default: HOST_CC or cc)",
    )
    parser.add_argument(
        "--expect-lifted",
        type=int,
        default=None,
        help="fail unless exactly this many addresses are managed by Progress 28",
    )
    parser.add_argument(
        "--no-verify",
        action="store_true",
        help="skip the host compiler probe (not recommended for commits)",
    )
    args = parser.parse_args()

    p16_rows = unique_rows(read_csv(P16_TARGETS), "P16")
    p17_rows = unique_rows(read_csv(P17_TARGETS), "P17")
    if len(p16_rows) != EXPECTED_P16:
        fail(f"expected {EXPECTED_P16} P16 rows, found {len(p16_rows)}")
    if len(p17_rows) != EXPECTED_P17:
        fail(f"expected {EXPECTED_P17} P17 rows, found {len(p17_rows)}")
    if set(p16_rows) & set(p17_rows):
        fail("P16/P17 address sets overlap")

    targets = unique_rows(read_csv(PROGRESS_TARGETS), "progress target")
    historical = set(p16_rows) | set(p17_rows)
    if not historical <= set(targets):
        fail("historical P16/P17 address outside progress_targets.csv")

    p16_chunks = split_snapshot(P16_SNAPSHOT)
    p17_chunks = split_snapshot(P17_SNAPSHOT)
    if set(p16_chunks) != set(p16_rows):
        fail("P16 target CSV and pseudocode markers differ")
    if set(p17_chunks) != set(p17_rows):
        fail("P17 target CSV and pseudocode markers differ")

    existing_promotions = read_csv(PROMOTIONS)
    promotion_map = unique_rows(existing_promotions, "source promotion")
    promoted = set(promotion_map)

    managed_existing = {
        address for address, row in promotion_map.items()
        if row.get("source_file", "").strip() == OUTPUT_REL
    }
    preexisting = promoted - managed_existing

    # Never replace a hand-reviewed/source-specific promotion.  On a rerun,
    # regenerate only our own corridor plus addresses not promoted elsewhere.
    managed_addresses = historical - preexisting
    if args.expect_lifted is not None and len(managed_addresses) != args.expect_lifted:
        fail(
            f"expected to manage {args.expect_lifted} addresses, "
            f"but current baseline requires {len(managed_addresses)}"
        )

    functions: list[LiftFunction] = []
    for address in sorted(managed_addresses, key=lambda value: int(value, 16)):
        if address in p16_rows:
            functions.append(
                parse_function(
                    address,
                    p16_chunks[address],
                    "P16",
                    targets[address],
                )
            )
        else:
            functions.append(
                parse_function(
                    address,
                    p17_chunks[address],
                    "P17",
                    targets[address],
                )
            )

    original_names = [function.original_name for function in functions]
    duplicates = sorted(
        name for name in set(original_names)
        if original_names.count(name) > 1
    )
    if duplicates:
        fail(f"duplicate decompiler function name in managed set: {duplicates[0]}")

    aliases: dict[str, str] = {}
    for function in functions:
        safe = f"snes_p28_{function.address[2:]}"
        aliases[function.original_name] = safe
        aliases.setdefault(f"FUN_{function.address[2:]}", safe)

    transformed_chunks: list[str] = []
    prototypes: list[str] = []

    for function in functions:
        text = function.raw_chunk
        # Calls between managed functions follow the new collision-proof address
        # names as well, including mapped functions whose Ghidra label was not
        # FUN_<address>.
        for old, new in sorted(aliases.items(), key=lambda item: len(item[0]), reverse=True):
            text = replace_identifier(text, old, new)
        text = normalize_chunk(text, function.address)

        header = (
            f"/* ===== {function.address} | {function.snapshot} | "
            f"{function.manifest_name} | {function.area} ===== */\n"
        )
        transformed = header + text.strip() + "\n"
        transformed_chunks.append(transformed)
        prototypes.append(function_prototype(transformed, function.address))

    body = "\n".join(transformed_chunks)

    if args.no_verify:
        source = assemble_source(body, prototypes)
    else:
        source = verify_with_compiler(body, prototypes, args.compiler)

    new_promotions = promotion_csv(
        existing_promotions,
        managed_existing | managed_addresses,
        functions,
    )

    # Validate the generated promotion universe before touching the working tree.
    generated_rows = unique_rows(
        list(csv.DictReader(io.StringIO(new_promotions))),
        "generated source promotion",
    )
    expected_promoted = preexisting | managed_addresses
    if set(generated_rows) != expected_promoted:
        fail(
            "generated promotion set differs from pre-existing + managed address universe"
        )
    if not historical <= set(generated_rows):
        missing = sorted(historical - set(generated_rows))[0]
        fail(f"historical source closure still misses {missing}")

    progress_doc = render_progress_doc(functions, len(preexisting), args.compiler)

    # Compiler verification and all set checks succeeded: mutation is now safe.
    atomic_write(OUTPUT, source)
    atomic_write(PROMOTIONS, new_promotions)
    atomic_write(PROGRESS_DOC, progress_doc)

    p16_lifted = sum(function.snapshot == "P16" for function in functions)
    p17_lifted = sum(function.snapshot == "P17" for function in functions)
    print(
        "Progress-28 source lift: OK "
        f"managed={len(functions)} (P16={p16_lifted}, P17={p17_lifted}) "
        f"preexisting={len(preexisting)} historical={EXPECTED_HISTORICAL}"
    )
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    print(f"updated {PROMOTIONS.relative_to(ROOT)}")
    print(f"generated {PROGRESS_DOC.relative_to(ROOT)}")
    print("Next gate: make audit-source && make check")


if __name__ == "__main__":
    main()
