#!/usr/bin/env python3
"""Generate docs/PROGRESS.generated.md from analysis/progress_targets.csv.

The project-wide percentage is intentionally a *coverage proxy* against the
1,137 heuristic JAL targets currently found by scan_calls.py. It is not a claim
that the ELF contains exactly 1,137 functions.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "analysis" / "progress_targets.csv"
OUT = ROOT / "docs" / "PROGRESS.generated.md"
JAL_CANDIDATE_PROXY = 1137

STATUS_ICON = {
    "MATCHING": "🟦",
    "RECONSTRUCTED": "🟩",
    "PARTIAL": "🟧",
    "IDENTIFIED": "🟨",
    "UNKNOWN": "⬜",
}

DRAW_FAMILY_START = 0x0018428C
DRAW_FAMILY_END = 0x0018BAC0


def pct(n: int, d: int) -> float:
    return 0.0 if not d else n * 100.0 / d


def main() -> None:
    rows = list(csv.DictReader(MANIFEST.open(encoding="utf-8")))
    for row in rows:
        row["addr_int"] = int(row["address"], 16)

    reconstructed = [r for r in rows if r["status"] in {"RECONSTRUCTED", "MATCHING"}]
    mapped = [r for r in rows if r["status"] != "UNKNOWN"]
    matching = [r for r in rows if r["status"] == "MATCHING"]

    draw = [
        r for r in rows
        if r["area"] == "renderer"
        and DRAW_FAMILY_START <= r["addr_int"] <= DRAW_FAMILY_END
        and r["addr_int"] < 0x001AC000
    ]
    draw.sort(key=lambda r: r["addr_int"])
    draw_recon = [r for r in draw if r["status"] in {"RECONSTRUCTED", "MATCHING"}]
    draw_mapped = [r for r in draw if r["status"] != "UNKNOWN"]

    # Fifteen squares per row keeps the exact 30-function draw-family map compact.
    blocks = [STATUS_ICON[r["status"]] for r in draw]
    grid_lines = ["".join(blocks[i:i+15]) for i in range(0, len(blocks), 15)]

    text = f"""# Generated progress snapshot

> Generated by `tools/update_progress.py`. Do not hand-edit this file.

## Project-wide coverage proxy

The current call-target scanner finds **{JAL_CANDIDATE_PROXY:,} heuristic JAL targets** in the analysis image. This is a deliberately conservative denominator and is **not** asserted to be the exact function count.

| Metric | Count | Proxy |
|---|---:|---:|
| Matching | {len(matching)} | **{pct(len(matching), JAL_CANDIDATE_PROXY):.2f}%** |
| Reconstructed / matching | {len(reconstructed)} | **{pct(len(reconstructed), JAL_CANDIDATE_PROXY):.2f}%** |
| Mapped (identified + partial + reconstructed) | {len(mapped)} | **{pct(len(mapped), JAL_CANDIDATE_PROXY):.2f}%** |

## Renderer draw-family map

This grid is exact for the **30 macro-expanded draw-family entry points from `0x0018428c` through `0x0018bac0`** currently tracked in `docs/RENDERER_MAP.md`.

- **Reconstructed:** {len(draw_recon)}/{len(draw)} = **{pct(len(draw_recon), len(draw)):.1f}%**
- **Mapped:** {len(draw_mapped)}/{len(draw)} = **{pct(len(draw_mapped), len(draw)):.1f}%**

```text
{chr(10).join(grid_lines)}
```

Legend: 🟩 reconstructed · 🟨 identified · 🟧 partial · ⬜ unknown · 🟦 matching

Each square corresponds to one function boundary, in ascending address order. The address/status table is sourced from [`analysis/progress_targets.csv`](../analysis/progress_targets.csv).

## Why there are multiple percentages

A decomp project can measure different things. **Matching** means rebuilt code is proven to reproduce the target machine code; **reconstructed** means source behavior/structure has been recovered but is not yet compiler-matched; **mapped** includes high-confidence identifications that still need source reconstruction.

Until the original compiler/toolchain fingerprint is nailed down, the reconstructed and renderer percentages are more useful than the matching percentage.
"""
    OUT.write_text(text, encoding="utf-8")

    readme = ROOT / "README.md"
    readme_text = readme.read_text(encoding="utf-8")
    start = "<!-- DECOMP_PROGRESS_START -->"
    end = "<!-- DECOMP_PROGRESS_END -->"
    block = f"""{start}
## Decompilation progress

> Percentages are evidence-based proxies, not a claim that the complete ELF has exactly {JAL_CANDIDATE_PROXY:,} functions. See [`docs/PROGRESS.generated.md`](docs/PROGRESS.generated.md) for the measurement rules.

- **Matching:** {pct(len(matching), JAL_CANDIDATE_PROXY):.2f}%
- **Reconstructed:** **{pct(len(reconstructed), JAL_CANDIDATE_PROXY):.2f}%** ({len(reconstructed)} tracked targets)
- **Mapped / identified:** **{pct(len(mapped), JAL_CANDIDATE_PROXY):.2f}%** ({len(mapped)} tracked targets)
- **Renderer draw family:** **{pct(len(draw_recon), len(draw)):.1f}% reconstructed / {pct(len(draw_mapped), len(draw)):.1f}% mapped**

```text
{chr(10).join(grid_lines)}
```

🟩 reconstructed · 🟨 identified · 🟧 partial · ⬜ unknown · 🟦 matching

The renderer grid contains one square per tracked draw-family function, ordered by address.
{end}"""
    if start in readme_text and end in readme_text:
        before = readme_text.split(start, 1)[0]
        after = readme_text.split(end, 1)[1]
        readme_text = before + block + after
    else:
        anchor = "> **Status:** active reverse engineering. The project is not yet buildable as a complete replacement ELF.\n"
        readme_text = readme_text.replace(anchor, anchor + "\n" + block + "\n")
    readme.write_text(readme_text, encoding="utf-8")

    print(f"wrote {OUT.relative_to(ROOT)} and README progress block")
    print(f"matching={len(matching)} reconstructed={len(reconstructed)} mapped={len(mapped)}")
    print(f"draw_reconstructed={len(draw_recon)}/{len(draw)} draw_mapped={len(draw_mapped)}/{len(draw)}")


if __name__ == "__main__":
    main()
